import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../../../core/api/client'
import { useAuth } from '../../../core/auth/context'
import { userQueryKey } from '../../../core/workspace/query'
import { Badge, Button, Card, PageContainer, PageHeader, inputClass } from '../../../components/ui'

export function UsersPage() {
  const client = useQueryClient()
  const userID = useAuth().user?.id
  const users = useQuery({ queryKey: userQueryKey(userID, 'users'), queryFn: api.users.list })
  const roles = useQuery({ queryKey: userQueryKey(userID, 'platform-roles'), queryFn: api.access.roles })
  const [form, setForm] = useState({ email: '', display_name: '', password: '' })
  const [editing, setEditing] = useState<{ id: string; display_name: string } | null>(null)
  const [error, setError] = useState('')
  const create = useMutation({ mutationFn: () => api.users.create(form), onSuccess: () => { setForm({ email: '', display_name: '', password: '' }); void client.invalidateQueries({ queryKey: userQueryKey(userID, 'users') }) }, onError: reason => setError(reason.message) })
  const status = useMutation({ mutationFn: ({ id, value }: { id: string; value: 'enable' | 'disable' }) => api.users.setStatus(id, value), onSuccess: () => void client.invalidateQueries({ queryKey: userQueryKey(userID, 'users') }) })
  const assign = useMutation({ mutationFn: ({ id, roleId }: { id: string; roleId: string }) => api.users.replaceRoles(id, roleId ? [roleId] : []), onSuccess: () => setError('') })
  const update = useMutation({ mutationFn: ({ id, display_name }: { id: string; display_name: string }) => api.users.update(id, { display_name }), onSuccess: () => { setEditing(null); void client.invalidateQueries({ queryKey: userQueryKey(userID, 'users') }) } })
  return <PageContainer variant="workspace"><PageHeader eyebrow="Administration" title="Users" description="Manage identities, status, and role assignments." /><div className="grid gap-5 lg:grid-cols-[minmax(260px,0.8fr)_minmax(0,2fr)]"><Card className="h-fit p-5"><form onSubmit={event => { event.preventDefault(); setError(''); create.mutate() }}><h2 className="mb-4 font-semibold">Create user</h2>{(['email', 'display_name', 'password'] as const).map(field => <label key={field} className="mb-3 block text-sm font-medium text-foreground">{field === 'display_name' ? 'Display name' : field[0].toUpperCase() + field.slice(1)}<input required value={form[field]} type={field === 'password' ? 'password' : field === 'email' ? 'email' : 'text'} onChange={event => setForm({ ...form, [field]: event.target.value })} className={inputClass} /></label>)}{error && <p className="mb-3 text-sm text-destructive">{error}</p>}<Button type="submit" disabled={create.isPending} className="w-full">{create.isPending ? 'Creating…' : 'Create user'}</Button></form></Card><Card className="overflow-hidden"><div className="border-b border-border px-5 py-4 font-semibold">All users</div><div className="divide-y divide-border">{users.isLoading && <p className="p-5 text-muted-foreground">Loading…</p>}{users.data?.map(user => <div key={user.id} className="grid gap-3 px-5 py-4 md:grid-cols-[1fr_auto_auto] md:items-center"><div>{editing?.id === user.id ? <div className="flex gap-2"><input value={editing.display_name} onChange={event => setEditing({ ...editing, display_name: event.target.value })} className={inputClass} /><Button variant="ghost" onClick={() => update.mutate(editing)}>Save</Button></div> : <button onClick={() => setEditing({ id: user.id, display_name: user.display_name })} className="text-left"><p className="font-medium hover:text-primary">{user.display_name}</p><p className="text-sm text-muted-foreground">{user.email}</p></button>}</div><div className="flex items-center gap-2"><Badge tone={user.status === 'active' ? 'success' : 'warning'}>{user.status}</Badge><select aria-label={`Role for ${user.email}`} onChange={event => assign.mutate({ id: user.id, roleId: event.target.value })} className={inputClass}><option value="">Assign role…</option>{roles.data?.map(role => <option key={role.id} value={role.id}>{role.display_name}</option>)}</select></div><Button variant="ghost" onClick={() => status.mutate({ id: user.id, value: user.status === 'active' ? 'disable' : 'enable' })}>{user.status === 'active' ? 'Disable' : 'Enable'}</Button></div>)}</div></Card></div></PageContainer>
}
