package metadata

import (
	"github.com/st-mich43l/apexvoid-CRM/internal/framework/entity"
	"github.com/st-mich43l/apexvoid-CRM/internal/framework/event"
	"github.com/st-mich43l/apexvoid-CRM/internal/framework/field"
	"github.com/st-mich43l/apexvoid-CRM/internal/framework/module"
	"github.com/st-mich43l/apexvoid-CRM/internal/framework/permission"
)

func Register(ctx *module.Context) error {
	for _, p := range []permission.Definition{{Name: "crm.pipeline.read", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "View CRM pipelines", Description: "Allows viewing sales pipeline configuration."}, {Name: "crm.pipeline.manage", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "Manage CRM pipelines", Description: "Allows creating and maintaining pipelines."}, {Name: "crm.stage.manage", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "Manage CRM stages", Description: "Allows configuring CRM pipeline stages."}, {Name: "crm.lead.read", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "View leads", Description: "Allows viewing CRM leads."}, {Name: "crm.lead.create", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "Create leads", Description: "Allows creating CRM leads."}, {Name: "crm.lead.update", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "Update leads", Description: "Allows editing and qualifying CRM leads."}, {Name: "crm.lead.convert", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "Convert leads", Description: "Allows converting qualified leads to opportunities."}, {Name: "crm.opportunity.read", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "View opportunities", Description: "Allows viewing CRM opportunities."}, {Name: "crm.opportunity.create", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "Create opportunities", Description: "Allows creating CRM opportunities."}, {Name: "crm.opportunity.update", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "Update opportunities", Description: "Allows editing CRM opportunities."}, {Name: "crm.opportunity.transition", Module: "crm", Scope: permission.ScopeWorkspace, DisplayName: "Transition opportunities", Description: "Allows moving and closing CRM opportunities."}} {
		if err := ctx.Permissions.Register(p); err != nil {
			return err
		}
	}
	for _, e := range []entity.Definition{{Name: "crm.pipeline", DisplayName: "Sales Pipeline", Module: "crm", Scope: entity.ScopeWorkspace, Fields: []field.Definition{{Name: "id", DisplayName: "ID", Type: field.UUID, ReadOnly: true}, {Name: "name", DisplayName: "Name", Type: field.String, Required: true}, {Name: "status", DisplayName: "Status", Type: field.Enum, Required: true}}}, {Name: "crm.stage", DisplayName: "Pipeline Stage", Module: "crm", Scope: entity.ScopeWorkspace, Fields: []field.Definition{{Name: "id", DisplayName: "ID", Type: field.UUID, ReadOnly: true}, {Name: "pipeline_id", DisplayName: "Pipeline", Type: field.RelationField, Required: true, Relation: &field.Relation{Kind: field.ManyToOne, Target: "crm.pipeline"}}, {Name: "name", DisplayName: "Name", Type: field.String, Required: true}, {Name: "category", DisplayName: "Category", Type: field.Enum, Required: true}}}, {Name: "crm.lead", DisplayName: "Lead", Module: "crm", Scope: entity.ScopeWorkspace, Fields: []field.Definition{{Name: "id", DisplayName: "ID", Type: field.UUID, ReadOnly: true}, {Name: "title", DisplayName: "Title", Type: field.String, Required: true}, {Name: "status", DisplayName: "Status", Type: field.Enum, Required: true}, {Name: "source", DisplayName: "Source", Type: field.String}, {Name: "contact_id", DisplayName: "Contact", Type: field.RelationField, Relation: &field.Relation{Kind: field.ManyToOne, Target: "contacts.contact"}}, {Name: "custom_values", DisplayName: "Custom values", Type: field.Text}}}, {Name: "crm.opportunity", DisplayName: "Opportunity", Module: "crm", Scope: entity.ScopeWorkspace, Fields: []field.Definition{{Name: "id", DisplayName: "ID", Type: field.UUID, ReadOnly: true}, {Name: "title", DisplayName: "Title", Type: field.String, Required: true}, {Name: "pipeline_id", DisplayName: "Pipeline", Type: field.RelationField, Required: true, Relation: &field.Relation{Kind: field.ManyToOne, Target: "crm.pipeline"}}, {Name: "stage_id", DisplayName: "Stage", Type: field.RelationField, Required: true, Relation: &field.Relation{Kind: field.ManyToOne, Target: "crm.stage"}}, {Name: "expected_revenue", DisplayName: "Expected revenue", Type: field.Decimal, Required: true}, {Name: "currency", DisplayName: "Currency", Type: field.Enum, Required: true}, {Name: "custom_values", DisplayName: "Custom values", Type: field.Text}}}} {
		if err := ctx.Entities.Register(e); err != nil {
			return err
		}
	}
	for _, item := range []event.Definition{{Name: "crm.lead.created", Module: "crm", Description: "Published after a lead is created."}, {Name: "crm.lead.updated", Module: "crm", Description: "Published after a lead is updated."}, {Name: "crm.lead.qualified", Module: "crm", Description: "Published after a lead is qualified."}, {Name: "crm.lead.disqualified", Module: "crm", Description: "Published after a lead is disqualified."}, {Name: "crm.lead.converted", Module: "crm", Description: "Published after a lead is converted."}, {Name: "crm.opportunity.created", Module: "crm", Description: "Published after an opportunity is created."}, {Name: "crm.opportunity.updated", Module: "crm", Description: "Published after an opportunity is updated."}, {Name: "crm.opportunity.stage_changed", Module: "crm", Description: "Published after an opportunity stage changes."}, {Name: "crm.opportunity.won", Module: "crm", Description: "Published after an opportunity is won."}, {Name: "crm.opportunity.lost", Module: "crm", Description: "Published after an opportunity is lost."}, {Name: "crm.opportunity.reopened", Module: "crm", Description: "Published after an opportunity is reopened."}} {
		if err := ctx.Events.Register(item); err != nil {
			return err
		}
	}
	return nil
}
