import { ClipboardList, ContactRound, Settings2, UserRound, Building2 } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { api, type ContactInput } from '../../core/api/client'
import { useAuth } from '../../core/auth/context'
import { useWorkspace } from '../../core/workspace/context'
import { userWorkspaceQueryKey } from '../../core/workspace/query'
import type { AppModule } from '../../framework/module/types'

const empty: ContactInput = { kind: 'person', display_name: '', email: '', phone: '', website: '', description: '', custom_values: {} }
function useContactKey(part: string) { const { user } = useAuth(); const { activeWorkspaceId } = useWorkspace(); return userWorkspaceQueryKey(user?.id, activeWorkspaceId, 'contacts', part) }

export function ContactsListPage() {
  const location = useLocation(); const kind = location.pathname.endsWith('companies') ? 'company' : location.pathname.endsWith('people') ? 'person' : undefined; const { activeWorkspaceId, can } = useWorkspace(); const key = useContactKey(`${kind ?? 'all'}-list`); const [search, setSearch] = useState(''); const [form, setForm] = useState<ContactInput>({ ...empty, kind: kind ?? 'person' }); const client = useQueryClient(); const contacts = useQuery({ queryKey: [...key, search], queryFn: () => api.contacts.list({ search, kind }), enabled: Boolean(activeWorkspaceId && can('contacts.contact.read')) }); const create = useMutation({ mutationFn: () => api.contacts.create(form), onSuccess: () => { setForm({ ...empty, kind: kind ?? 'person' }); void client.invalidateQueries({ queryKey: key }) } });
  const title = kind === 'company' ? 'Companies' : kind === 'person' ? 'People' : 'Contacts';
  return <section><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.2em] text-primary">Contacts</p><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 text-muted-foreground">Shared business records for your current workspace.</p></div><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search contacts" className="rounded-lg border border-border bg-card px-3 py-2 text-sm" /></div>{!can('contacts.contact.read') ? <Empty text="You do not have permission to view contacts." /> : <div className="grid gap-6 lg:grid-cols-[1fr_2fr]"><form onSubmit={event => { event.preventDefault(); create.mutate() }} className="h-fit rounded-xl border border-border bg-card p-5"><h2 className="mb-4 font-semibold">Add contact</h2><select value={form.kind} onChange={event => setForm({ ...form, kind: event.target.value as ContactInput['kind'] })} className="mb-3 w-full rounded-lg border border-border bg-background px-3 py-2"><option value="person">Person</option><option value="company">Company</option></select><input required value={form.display_name} onChange={event => setForm({ ...form, display_name: event.target.value })} placeholder="Display name" className="mb-3 w-full rounded-lg border border-border bg-background px-3 py-2" /><input value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} placeholder="Email" className="mb-3 w-full rounded-lg border border-border bg-background px-3 py-2" />{can('contacts.contact.create') && <button disabled={create.isPending} className="w-full rounded-lg bg-primary px-3 py-2 font-semibold text-primary-foreground">Create</button>}</form><div className="rounded-xl border border-border bg-card"><div className="divide-y divide-border">{contacts.data?.items.map(contact => <Link key={contact.id} to={`/contacts/${contact.id}`} className="flex items-center justify-between px-5 py-4 hover:bg-muted"><span><span className="block font-medium">{contact.display_name}</span><span className="text-sm text-muted-foreground">{contact.email || contact.kind}</span></span><span className="text-xs uppercase text-muted-foreground">{contact.status}</span></Link>)}{contacts.data?.items.length === 0 && <Empty text="No contacts found." />}{contacts.isLoading && <Empty text="Loading contacts…" />}</div></div></div>}</section>
}

export function ContactDetailPage() { const { id = '' } = useParams(); const { can } = useWorkspace(); const contact = useQuery({ queryKey: useContactKey(`detail-${id}`), queryFn: () => api.contacts.get(id), enabled: Boolean(id && can('contacts.contact.read')) }); const notesKey = useContactKey(`notes-${id}`); const notes = useQuery({ queryKey: notesKey, queryFn: () => api.contacts.notes(id), enabled: Boolean(contact.data) }); const [note, setNote] = useState(''); const client = useQueryClient(); const addNote = useMutation({ mutationFn: () => api.contacts.createNote(id, note), onSuccess: () => { setNote(''); void client.invalidateQueries({ queryKey: notesKey }) } }); if (!contact.data) return <Empty text={contact.isLoading ? 'Loading contact…' : 'Contact not found.'} />; return <section><Link to="/contacts/people" className="text-sm text-primary">← Back to contacts</Link><div className="mb-8 mt-4"><p className="text-sm uppercase tracking-[0.2em] text-primary">{contact.data.kind}</p><h1 className="mt-2 text-3xl font-semibold">{contact.data.display_name}</h1><p className="mt-2 text-muted-foreground">{contact.data.email || 'No email recorded'}</p></div><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-border bg-card p-5"><h2 className="mb-3 font-semibold">Profile</h2><dl className="space-y-3 text-sm"><div><dt className="text-muted-foreground">Phone</dt><dd>{contact.data.phone || '—'}</dd></div><div><dt className="text-muted-foreground">Website</dt><dd>{contact.data.website || '—'}</dd></div><div><dt className="text-muted-foreground">Status</dt><dd>{contact.data.status}</dd></div></dl></div><div className="rounded-xl border border-border bg-card p-5"><h2 className="mb-3 font-semibold">Notes</h2>{notes.data?.map(item => <p key={item.id} className="mb-2 rounded-lg bg-muted p-3 text-sm">{item.content}</p>)}{can('contacts.note.manage') && <form onSubmit={event => { event.preventDefault(); addNote.mutate() }} className="mt-4 flex gap-2"><input required value={note} onChange={event => setNote(event.target.value)} placeholder="Add a note" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm" /><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground">Add</button></form>}</div></div></section> }

export function ActivitiesPage() { const { user } = useAuth(); const { activeWorkspaceId, can } = useWorkspace(); const query = useQuery({ queryKey: useContactKey('activities'), queryFn: () => api.contacts.activities(), enabled: Boolean(activeWorkspaceId && can('contacts.activity.read')) }); return <section><div className="mb-8"><p className="text-sm uppercase tracking-[0.2em] text-primary">Contacts</p><h1 className="mt-2 text-3xl font-semibold">Activities</h1><p className="mt-2 text-muted-foreground">Calls, meetings, follow-ups, and tasks.</p></div>{!can('contacts.activity.read') ? <Empty text="You do not have permission to view activities." /> : <div className="rounded-xl border border-border bg-card divide-y divide-border">{query.data?.map(activity => <div key={activity.id} className="px-5 py-4"><p className="font-medium">{activity.title}</p><p className="text-sm text-muted-foreground">{activity.activity_type} · {activity.status} · {activity.assigned_user_id === user?.id ? 'assigned to you' : 'assigned to a teammate'}</p></div>)}{query.data?.length === 0 && <Empty text="No activities yet." />}</div>}</section> }

export function ContactsSettingsPage() { const { can } = useWorkspace(); const fields = useQuery({ queryKey: useContactKey('fields'), queryFn: api.contacts.fields, enabled: can('contacts.field.manage') }); return <section><div className="mb-8"><p className="text-sm uppercase tracking-[0.2em] text-primary">Contacts</p><h1 className="mt-2 text-3xl font-semibold">Contacts settings</h1><p className="mt-2 text-muted-foreground">Configure the shared record foundation for this workspace.</p></div>{!can('contacts.field.manage') ? <Empty text="You do not have permission to manage contact settings." /> : <div className="rounded-xl border border-border bg-card p-5"><h2 className="mb-4 font-semibold">Custom fields</h2>{fields.data?.map(field => <div key={field.id} className="flex justify-between border-b border-border py-3 text-sm"><span>{field.label}</span><span className="text-muted-foreground">{field.type}{field.required ? ' · required' : ''}</span></div>)}{fields.data?.length === 0 && <Empty text="No custom fields configured." />}</div>}</section> }

function Empty({ text }: { text: string }) { return <div className="p-8 text-center text-sm text-muted-foreground">{text}</div> }

// eslint-disable-next-line react-refresh/only-export-components
export const contactsModule: AppModule = { name: 'contacts', version: '1.0.0', dependencies: ['core'], routes: [{ id: 'contacts-people', path: '/contacts/people', element: <ContactsListPage /> }, { id: 'contacts-companies', path: '/contacts/companies', element: <ContactsListPage /> }, { id: 'contacts-detail', path: '/contacts/:id', element: <ContactDetailPage /> }, { id: 'contacts-activities', path: '/contacts/activities', element: <ActivitiesPage /> }, { id: 'contacts-settings', path: '/contacts/settings', element: <ContactsSettingsPage /> }], navigation: [{ id: 'contacts-people', label: 'People', path: '/contacts/people', order: 300, icon: UserRound, permission: { scope: 'workspace', name: 'contacts.contact.read' } }, { id: 'contacts-companies', label: 'Companies', path: '/contacts/companies', order: 301, icon: Building2, permission: { scope: 'workspace', name: 'contacts.contact.read' } }, { id: 'contacts-activities', label: 'Activities', path: '/contacts/activities', order: 302, icon: ClipboardList, permission: { scope: 'workspace', name: 'contacts.activity.read' } }, { id: 'contacts-settings', label: 'Contact settings', path: '/contacts/settings', order: 910, icon: Settings2, permission: { scope: 'workspace', name: 'contacts.field.manage' } }, { id: 'contacts', label: 'Contacts', path: '/contacts/people', order: 299, icon: ContactRound, permission: { scope: 'workspace', name: 'contacts.contact.read' } }] }
