import { Activity, ArrowRight, Boxes, Building2, CheckCircle2, ContactRound, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { api } from '../../../core/api/client'
import { useWorkspace } from '../../../core/workspace/context'
import { Badge, Button, Card, CardHeader, EmptyState, PageContainer, PageHeader } from '../../../components/ui'

export function DashboardPage() {
  const health = useQuery({ queryKey: ['health'], queryFn: api.health, retry: 1 })
  const readiness = useQuery({ queryKey: ['readiness'], queryFn: api.readiness, retry: 1 })
  const { activeWorkspace } = useWorkspace()
  const services = [{ label: 'API service', value: health.data?.status === 'ok' ? 'Healthy' : 'Unavailable', icon: Activity, tone: health.data?.status === 'ok' ? 'success' : 'warning' }, { label: 'Database', value: readiness.data?.dependencies.postgres === 'ok' ? 'Connected' : 'Unavailable', icon: ShieldCheck, tone: readiness.data?.dependencies.postgres === 'ok' ? 'success' : 'warning' }, { label: 'Workspace', value: activeWorkspace?.name ?? 'Not selected', icon: Boxes, tone: activeWorkspace ? 'primary' : 'neutral' }] satisfies Array<{ label: string; value: string; icon: typeof Activity; tone: 'success' | 'warning' | 'primary' | 'neutral' }>
  return <PageContainer variant="workspace"><PageHeader eyebrow="ApexVoid CRM" title={activeWorkspace ? `Good morning, ${activeWorkspace.name}` : 'ApexVoid is ready'} description="A focused home for the applications and work your team runs every day." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{services.map(({ label, value, icon: Icon, tone }) => <Card key={label} className="p-4"><div className="flex items-center justify-between"><span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</span><Icon size={17} className="text-primary" /></div><div className="mt-5 flex items-center justify-between gap-3"><p className="truncate text-sm font-semibold text-foreground">{value}</p><Badge tone={tone}>{tone === 'success' ? 'Ready' : tone === 'warning' ? 'Check' : 'Current'}</Badge></div></Card>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><Card><CardHeader title="Start with a workspace" description="Jump into the areas that are ready for your team." /><div className="grid gap-2 p-3 sm:grid-cols-3"><QuickLink to="/contacts/people" icon={ContactRound} label="People" /><QuickLink to="/contacts/companies" icon={Building2} label="Companies" /><QuickLink to="/contacts/activities" icon={Activity} label="Activities" /></div></Card><Card><CardHeader title="Getting started" description="Keep the foundation healthy as your workspace grows." /><div className="p-5"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-success" size={18} /><div><p className="text-sm font-medium">Workspace foundation is ready</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Configure members, roles and contact settings when you are ready to invite the team.</p><Link to="/settings" className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline">Open settings <ArrowRight size={14} /></Link></div></div></div></Card></div><Card className="mt-5"><EmptyState title="No upcoming activity yet" description="Scheduled calls, meetings and follow-ups will appear here once your team starts working in the workspace." action={<Link to="/contacts/activities"><Button variant="outline">View activities</Button></Link>} /></Card></PageContainer>
}

function QuickLink({ to, icon: Icon, label }: { to: string; icon: typeof ContactRound; label: string }) { return <Link to={to} className="group flex items-center gap-3 rounded-lg border border-transparent px-3 py-3 transition hover:border-border hover:bg-muted"><span className="grid h-8 w-8 place-items-center rounded-lg bg-primary/10 text-primary"><Icon size={16} /></span><span className="text-sm font-medium">{label}</span><ArrowRight size={14} className="ml-auto text-muted-foreground opacity-0 transition group-hover:opacity-100" /></Link> }
