import { useState, type FormEvent } from 'react'
import { Button, Card, inputClass } from '../../../components/ui'
import type { ExternalIntegration, ExternalIntegrationInput } from '../../../core/api/client'

type Props = { initial?: ExternalIntegration; pending?: boolean; error?: string; onCancel: () => void; onSubmit: (input: ExternalIntegrationInput) => Promise<void> }
type PermissionDraft = { name: string; display_name: string; description: string; scope: 'platform' | 'workspace' }

function initialValue(item?: ExternalIntegration): ExternalIntegrationInput {
  return item ? { id: item.id, display_name: item.display_name, description: item.description, version: item.version, api_contract_version: 'v1', service_identity: item.service_identity, service_endpoint: item.service_endpoint, health_endpoint: item.health_endpoint, frontend_route: item.frontend_route, settings_route: item.settings_route, access_match: item.access_match as 'all' | 'any', access_permissions: item.access_permissions, permissions: item.permissions } : { id: '', display_name: '', description: '', version: '1.0.0', api_contract_version: 'v1', service_identity: '', service_endpoint: '', health_endpoint: '', frontend_route: '', settings_route: '', access_match: 'all', access_permissions: [], permissions: [{ name: '', display_name: '', description: '', scope: 'workspace' }] }
}

export function ExternalIntegrationEditor({ initial, pending, error, onCancel, onSubmit }: Props) {
  const [draft, setDraft] = useState(initialValue(initial))
  const [validation, setValidation] = useState('')
  const update = (field: keyof ExternalIntegrationInput, value: string | string[]) => setDraft(current => ({ ...current, [field]: value }))
  const updatePermission = (index: number, field: keyof PermissionDraft, value: string) => setDraft(current => ({ ...current, permissions: current.permissions.map((permission, position) => position === index ? { ...permission, [field]: value } : permission) }))
  const submit = async (event: FormEvent) => {
    event.preventDefault()
    const normalized = { ...draft, id: draft.id.trim(), display_name: draft.display_name.trim(), description: draft.description.trim(), version: draft.version.trim(), service_identity: draft.service_identity.trim(), service_endpoint: draft.service_endpoint.trim(), health_endpoint: draft.health_endpoint.trim(), frontend_route: draft.frontend_route.trim(), settings_route: draft.settings_route?.trim(), permissions: draft.permissions.map(permission => ({ ...permission, name: permission.name.trim(), display_name: permission.display_name.trim(), description: permission.description?.trim() ?? '' })), access_permissions: draft.access_permissions.filter(Boolean) }
    if (!normalized.id || !normalized.display_name || !normalized.service_identity || !normalized.service_endpoint || !normalized.health_endpoint || !normalized.frontend_route || normalized.permissions.some(permission => !permission.name || !permission.display_name)) { setValidation('Complete the required identity, endpoint, route, and permission fields.'); return }
    if (!normalized.access_permissions.length) { setValidation('Choose at least one declared permission for application entry.'); return }
    setValidation('')
    await onSubmit(normalized)
  }
  return <Card className="mb-5 p-5 sm:p-6"><form className="space-y-5" onSubmit={event => void submit(event)}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-semibold">{initial ? `Edit ${initial.display_name}` : 'Register trusted external application'}</h2><p className="mt-1 text-sm text-muted-foreground">Only allowlisted Docker service hosts can be registered. Permission names and application ID are immutable after registration.</p></div><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button></div>
    {(validation || error) && <p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2 text-sm text-destructive">{validation || error}</p>}
    <div className="grid gap-4 md:grid-cols-2"><Field label="Application ID" value={draft.id} disabled={Boolean(initial)} placeholder="reports" onChange={value => update('id', value)} /><Field label="Display name" value={draft.display_name} placeholder="Reports" onChange={value => update('display_name', value)} /><Field label="Application version" value={draft.version} placeholder="1.0.0" onChange={value => update('version', value)} /><label className="text-sm font-medium">API contract<select className={inputClass} value="v1" disabled><option value="v1">v1 · supported</option></select></label><Field label="Service identity" value={draft.service_identity} placeholder="reports-service" onChange={value => update('service_identity', value)} /><Field label="Frontend route" value={draft.frontend_route} placeholder="/apps/reports" onChange={value => update('frontend_route', value)} /><Field label="Service endpoint" value={draft.service_endpoint} placeholder="http://reports-service:8090" onChange={value => update('service_endpoint', value)} /><Field label="Health endpoint" value={draft.health_endpoint} placeholder="http://reports-service:8090/health" onChange={value => update('health_endpoint', value)} /><Field label="Settings route (optional)" value={draft.settings_route ?? ''} placeholder="/apps/reports/settings" onChange={value => update('settings_route', value)} /></div>
    <label className="block text-sm font-medium">Description<textarea className={`${inputClass} min-h-20 py-2`} value={draft.description} onChange={event => update('description', event.target.value)} /></label>
    <fieldset className="rounded-xl border border-border p-4"><legend className="px-1 text-sm font-semibold">Application permissions</legend><p className="mb-3 text-xs text-muted-foreground">Declare only names owned by this application, for example <code>reports.report.read</code>. Names and scopes are immutable after registration.</p><div className="space-y-3">{draft.permissions.map((permission, index) => <div key={index} className="grid gap-2 rounded-lg bg-muted/40 p-3 md:grid-cols-[1.3fr_1fr_1fr_9rem_auto]"><input aria-label={`Permission ${index + 1} name`} className={inputClass} value={permission.name} placeholder="reports.report.read" disabled={Boolean(initial)} onChange={event => updatePermission(index, 'name', event.target.value)} /><input aria-label={`Permission ${index + 1} display name`} className={inputClass} value={permission.display_name} placeholder="Read reports" onChange={event => updatePermission(index, 'display_name', event.target.value)} /><input aria-label={`Permission ${index + 1} description`} className={inputClass} value={permission.description} placeholder="Optional description" onChange={event => updatePermission(index, 'description', event.target.value)} /><select aria-label={`Permission ${index + 1} scope`} className={inputClass} value={permission.scope} disabled={Boolean(initial)} onChange={event => updatePermission(index, 'scope', event.target.value)}><option value="workspace">Workspace</option><option value="platform">Platform</option></select><Button type="button" variant="ghost" disabled={draft.permissions.length === 1 || Boolean(initial)} onClick={() => setDraft(current => ({ ...current, permissions: current.permissions.filter((_, position) => position !== index), access_permissions: current.access_permissions.filter(name => name !== permission.name) }))}>Remove</Button></div>)}</div>{!initial && <Button type="button" className="mt-3" variant="outline" onClick={() => setDraft(current => ({ ...current, permissions: [...current.permissions, { name: '', display_name: '', description: '', scope: 'workspace' }] }))}>Add permission</Button>}</fieldset>
    <fieldset className="rounded-xl border border-border p-4"><legend className="px-1 text-sm font-semibold">Entry authorization</legend><div className="mt-2 flex flex-wrap items-center gap-3"><label className="text-sm">Match<select className={`${inputClass} inline-block w-auto`} value={draft.access_match} onChange={event => update('access_match', event.target.value)}><option value="all">All selected permissions</option><option value="any">Any selected permission</option></select></label><span className="text-xs text-muted-foreground">Entry access is separate from per-operation checks in the service.</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{draft.permissions.map((permission, index) => <label key={`${permission.name}-${index}`} className="flex min-h-9 items-center gap-2 rounded-lg border border-border px-3 text-sm"><input type="checkbox" checked={draft.access_permissions.includes(permission.name)} disabled={!permission.name} onChange={() => setDraft(current => ({ ...current, access_permissions: current.access_permissions.includes(permission.name) ? current.access_permissions.filter(name => name !== permission.name) : [...current.access_permissions, permission.name] }))} />{permission.name || 'Name the permission first'}</label>)}</div></fieldset>
    <div className="flex flex-wrap justify-end gap-3"><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button><Button disabled={pending}>{pending ? 'Saving…' : initial ? 'Save metadata' : 'Register application'}</Button></div>
  </form></Card>
}

function Field({ label, value, placeholder, disabled, onChange }: { label: string; value: string; placeholder: string; disabled?: boolean; onChange: (value: string) => void }) {
  return <label className="text-sm font-medium">{label}<input className={inputClass} value={value} placeholder={placeholder} disabled={disabled} onChange={event => onChange(event.target.value)} /></label>
}
