import { Monitor, Moon, Sun } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useTheme } from '../../../core/theme/context'

export function SettingsPage() {
  const { preference, setPreference } = useTheme()
  const options = [{ value: 'light', label: 'Light', description: 'Bright and clear', icon: Sun }, { value: 'dark', label: 'Dark', description: 'Low-light comfort', icon: Moon }, { value: 'system', label: 'System', description: 'Follow your device', icon: Monitor }] as const

  return <div><p className="mb-3 text-sm font-medium text-primary">Workspace</p><h1 className="text-3xl font-semibold tracking-tight">Settings</h1><p className="mt-3 max-w-2xl text-muted-foreground">Keep your workspace focused. Manage its identity, team access, and appearance here.</p><div className="mt-8 grid gap-4 md:grid-cols-2"><Link to="/settings/organization" className="rounded-2xl border border-border bg-card p-6 transition hover:border-primary"><h2 className="font-medium text-foreground">Organization</h2><p className="mt-2 text-sm text-muted-foreground">Company name, workspace name, and timezone.</p></Link><Link to="/settings/members" className="rounded-2xl border border-border bg-card p-6 transition hover:border-primary"><h2 className="font-medium text-foreground">Members</h2><p className="mt-2 text-sm text-muted-foreground">Add existing users and manage workspace roles.</p></Link></div><section className="mt-8 rounded-2xl border border-border bg-card p-6"><div className="mb-5"><h2 className="font-medium text-foreground">Appearance</h2><p className="mt-2 text-sm text-muted-foreground">Choose how ApexVoid looks on this device.</p></div><div className="grid gap-3 sm:grid-cols-3">{options.map(({ value, label, description, icon: Icon }) => <button key={value} type="button" onClick={() => setPreference(value)} className={`rounded-xl border p-4 text-left transition ${preference === value ? 'border-primary bg-primary/10' : 'border-border bg-background hover:border-primary'}`}><Icon size={18} className={preference === value ? 'text-primary' : 'text-muted-foreground'} /><span className="mt-3 block text-sm font-medium text-foreground">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{description}</span></button>)}</div></section></div>
}
