import { Monitor, Moon, Sun } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useTheme } from '../../../core/theme/context'
import { Card, PageContainer, PageHeader } from '../../../components/ui'

export function SettingsPage() {
  const { preference, setPreference } = useTheme()
  const options = [{ value: 'light', label: 'Light', description: 'Bright and clear', icon: Sun }, { value: 'dark', label: 'Dark', description: 'Low-light comfort', icon: Moon }, { value: 'system', label: 'System', description: 'Follow your device', icon: Monitor }] as const

  return <PageContainer variant="settings"><PageHeader eyebrow="Workspace" title="Settings" description="Keep your workspace focused. Manage its identity, team access, and appearance here." /><div className="grid gap-4 md:grid-cols-2"><Link to="/settings/organization" className="group"><Card className="h-full p-6 transition hover:-translate-y-0.5 hover:border-primary"><h2 className="font-medium text-foreground group-hover:text-primary">Organization</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Company name, workspace name, and timezone.</p></Card></Link><Link to="/settings/members" className="group"><Card className="h-full p-6 transition hover:-translate-y-0.5 hover:border-primary"><h2 className="font-medium text-foreground group-hover:text-primary">Members</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Add existing users and manage workspace roles.</p></Card></Link></div><Card className="mt-5 p-6"><div className="mb-5"><h2 className="font-medium text-foreground">Appearance</h2><p className="mt-2 text-sm text-muted-foreground">Choose how ApexVoid looks on this device.</p></div><div className="grid gap-3 sm:grid-cols-3">{options.map(({ value, label, description, icon: Icon }) => <button key={value} type="button" onClick={() => setPreference(value)} aria-pressed={preference === value} className={`rounded-xl border p-4 text-left transition ${preference === value ? 'border-primary bg-primary/10' : 'border-border bg-background hover:border-primary'}`}><Icon size={18} className={preference === value ? 'text-primary' : 'text-muted-foreground'} /><span className="mt-3 block text-sm font-medium text-foreground">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{description}</span></button>)}</div></Card></PageContainer>
}
