import type { ButtonHTMLAttributes, ReactNode } from 'react'

export function PageContainer({ children, variant = 'workspace', className = '' }: { children: ReactNode; variant?: 'settings' | 'workspace' | 'detail'; className?: string }) {
  const widths = { settings: 'max-w-5xl', workspace: 'max-w-[1440px]', detail: 'max-w-6xl' }
  return <section className={`mx-auto w-full ${widths[variant]} ${className}`}>{children}</section>
}

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) {
  return <header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><>{eyebrow && <p className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary">{eyebrow}</p>}</><h1 className="text-[28px] font-semibold tracking-tight text-foreground sm:text-[30px]">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{actions && <div className="flex shrink-0 items-center gap-2">{actions}</div>}</header>
}

export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`rounded-xl border border-border bg-card shadow-[0_1px_2px_rgba(16,24,40,0.04)] ${className}`}>{children}</div> }
export function CardHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="flex items-start justify-between gap-4 border-b border-border px-5 py-4 sm:px-6"><div><h2 className="text-[15px] font-semibold text-card-foreground">{title}</h2>{description && <p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p>}</div>{action}</div> }
export function Button({ variant = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive' }) { const styles = { primary: 'bg-primary text-primary-foreground hover:opacity-90', secondary: 'bg-secondary text-secondary-foreground hover:bg-muted', outline: 'border border-border bg-card text-foreground hover:bg-muted', ghost: 'text-muted-foreground hover:bg-muted hover:text-foreground', destructive: 'bg-destructive text-destructive-foreground hover:opacity-90' }; return <button {...props} className={`inline-flex min-h-9 items-center justify-center rounded-lg px-3.5 text-sm font-medium transition disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} /> }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'danger' | 'primary' }) { const styles = { neutral: 'bg-muted text-muted-foreground', success: 'bg-success/10 text-success', warning: 'bg-warning/10 text-warning', danger: 'bg-destructive/10 text-destructive', primary: 'bg-primary/10 text-primary' }; return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-medium ${styles[tone]}`}>{children}</span> }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="flex min-h-44 flex-col items-center justify-center px-6 py-10 text-center"><p className="text-sm font-semibold text-foreground">{title}</p>{description && <p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">{description}</p>}{action && <div className="mt-4">{action}</div>}</div> }
export function LoadingState({ label = 'Loading…' }: { label?: string }) { return <div className="flex min-h-44 items-center justify-center text-sm text-muted-foreground"><span className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-primary/25 border-t-primary" />{label}</div> }
export function ErrorState({ message = 'Something went wrong.', onRetry }: { message?: string; onRetry?: () => void }) { return <div className="rounded-xl border border-destructive/25 bg-destructive/5 p-4 text-sm text-destructive">{message}{onRetry && <button onClick={onRetry} className="ml-3 underline underline-offset-2">Retry</button>}</div> }

export const inputClass = 'mt-1.5 min-h-10 w-full rounded-lg border border-input bg-background px-3 text-sm text-foreground outline-none transition placeholder:text-muted-foreground/70 focus:border-primary focus:ring-2 focus:ring-primary/15 disabled:cursor-not-allowed disabled:opacity-60'
